<? include_once('./php/hl/functions.php');?>
<html>
<head>
<title>Top 30 source contacts for the last 30 days</title>
</head>
<body>
<h1>Top 30 source contacts for the last 30 days</h1>
<table border=1>
<tr><td>Num Received</td><td>Source Contact</td><td>Comments</td></tr>
<tr>
<td>15745</td>
<td>postmaster@localhost</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>320</td>
<td>mail-abuse@cert.br</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>17</td>
<td>abuse@fastweb.it</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>11</td>
<td>abuse@telekomunikacja.pl</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>6</td>
<td>abuse@alestra.net.mx</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>5</td>
<td>customers@pldt.com.ph</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>3</td>
<td>abuse@telefonica.net</td>
<td>abuse email invalid</td>
</tr>
<tr>
<td>3</td>
<td>abuse@rr.com</td>
<td>abuse email invalid</td>
</tr>
<tr>
<td>3</td>
<td>abuse@ttnet.net.tr</td>
<td>abuse email auto-responds</td>
</tr>
<tr>
<td>3</td>
<td>abuse@interbusiness.it</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>3</td>
<td>abuse@bbtec.net</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>3</td>
<td>admin@satfilm.pl</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@comcast.net</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@business.telecomitalia.it</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>sugerencias@mipunto.com</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse-net-does-not-handle-ip-addresses@example.net</td>
<td>abuse email invalid</td>
</tr>
<tr>
<td>2</td>
<td>abuse@ntlworld.com</td>
<td>abuse email auto-responds</td>
</tr>
<tr>
<td>2</td>
<td>abuse@charter.net</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@att.net</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@gin.cz</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>netservice1@ct.cz</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@dialog.net.pl</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@cox.net</td>
<td>abuse email auto-responds</td>
</tr>
<tr>
<td>2</td>
<td>abuse@cdp.pl</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@moj.net</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>abuse@fpt.vn</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>2</td>
<td>internet.abuse@sjrb.ca</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>1</td>
<td>abuse@loxinfo.co.th</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>1</td>
<td>abuse@vnn.vn</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>1</td>
<td>mailto:abuse@proxad.net</td>
<td>&nbsp;</td>
</tr>
</table>
<hr>
<?php
$fnam="php/cnts/abuse30_stats_cnt.txt";
showCount($fnam,"");
?>
</body>
</html>
